import { Database, ExternalLink, MapPinned, Search } from 'lucide-react';
import { adminAttractions } from '../data';
import { PageHeading, Panel, TableShell, tdClass, thClass } from '../ui';

export function AttractionsPage() { return <><PageHeading eyebrow="Tourism data" title="관광지 데이터" description="추천에 사용된 공공 관광 데이터의 출처, 혼잡도와 숨은 명소 점수를 확인합니다." />
  <div className="mb-6 grid gap-4 sm:grid-cols-3"><DataMini label="저장된 추천 데이터" value="3,842" sub="+124 이번 주" /><DataMini label="TourAPI 비율" value="86%" sub="정상 수집 중" /><DataMini label="중복 의심 데이터" value="18" sub="검토 필요" warning /></div>
  <Panel><div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row"><div className="relative max-w-md flex-1"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input className="h-12 w-full rounded-2xl border border-slate-200 pl-11 pr-4 text-sm outline-none focus:border-[#ff5a47]" placeholder="관광지명, 주소, 출처 검색" /></div><select className="h-12 rounded-2xl border border-slate-200 bg-white px-4 text-sm font-bold"><option>전체 카테고리</option><option>관광지</option><option>문화시설</option><option>자연</option></select></div>
    <TableShell><thead><tr>{['관광지', '분류', '출처', '숨은 점수', '혼잡 점수', '추천 사용', ''].map(x => <th className={thClass} key={x}>{x}</th>)}</tr></thead><tbody>{adminAttractions.map(item => <tr className="hover:bg-slate-50/70" key={item.name}><td className={tdClass}><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-orange-50 text-orange-600"><MapPinned className="h-4 w-4" /></span><div><p className="font-black">{item.name}</p><p className="text-xs text-slate-400">{item.region}</p></div></div></td><td className={tdClass}><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-bold">{item.category}</span></td><td className={tdClass}><span className="flex items-center gap-1.5 text-xs font-black"><Database className="h-3.5 w-3.5 text-slate-400" />{item.source}</span></td><td className={tdClass}><Score value={item.hiddenScore} color="bg-emerald-500" /></td><td className={tdClass}><Score value={item.congestion} color="bg-orange-500" /></td><td className={`${tdClass} font-black`}>{item.used}회</td><td className={tdClass}><button className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200"><ExternalLink className="h-4 w-4" /></button></td></tr>)}</tbody></TableShell>
  </Panel></> }
function Score({ value, color }: { value: number; color: string }) { return <div className="flex items-center gap-2"><div className="h-1.5 w-16 rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{ width: `${value}%` }} /></div><span className="text-xs font-black">{value}</span></div>; }
function DataMini({ label, value, sub, warning }: { label: string; value: string; sub: string; warning?: boolean }) { return <div className="rounded-2xl border border-black/[.06] bg-white p-5"><p className="text-xs font-bold text-slate-400">{label}</p><div className="mt-2 flex items-end justify-between"><p className="text-2xl font-black">{value}</p><p className={`text-[11px] font-bold ${warning ? 'text-amber-600' : 'text-emerald-600'}`}>{sub}</p></div></div>; }
