import { Activity, AlertTriangle, Bot, CheckCircle2, Clock3, CloudSun, Database, KeyRound, Map } from 'lucide-react';
import { PageHeading, Panel } from '../ui';

const systems = [
  { name: 'OddTrip API', description: 'FastAPI 애플리케이션', icon: Database, status: '정상', latency: '42ms', checked: '방금 전' },
  { name: 'OpenAI', description: '관광지 · 일정 · 갈등 조정', icon: Bot, status: '정상', latency: '1.8s', checked: '1분 전' },
  { name: 'TourAPI 4.0', description: '한국관광공사 관광정보', icon: Map, status: '정상', latency: '312ms', checked: '2분 전' },
  { name: '기상청 API', description: '날씨 및 관광지 예보', icon: CloudSun, status: '정상', latency: '284ms', checked: '4분 전' },
  { name: 'Google Maps', description: '좌표 및 이동시간', icon: Map, status: '주의', latency: '920ms', checked: '2분 전' },
];

export function OperationsPage() { return <><PageHeading eyebrow="System health" title="운영 상태" description="외부 연동과 AI 기능의 응답 상태를 확인합니다. API 키 원문은 화면에 노출하지 않습니다." action={<button className="flex h-11 items-center gap-2 rounded-2xl bg-[#17201f] px-4 text-xs font-black text-white"><Activity className="h-4 w-4" />전체 상태 확인</button>} />
  <div className="mb-6 rounded-[24px] border border-emerald-200 bg-emerald-50 p-6"><div className="flex items-start gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-emerald-600 text-white"><CheckCircle2 /></span><div><h2 className="font-black text-emerald-900">핵심 서비스가 정상 작동 중입니다</h2><p className="mt-1 text-sm font-medium text-emerald-700">최근 24시간 API 성공률 99.82% · 평균 응답시간 386ms</p></div></div></div>
  <div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><Panel><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-black">연동 서비스</h2><span className="text-[11px] font-bold text-slate-400">자동 새로고침 5분</span></div><div className="space-y-2">{systems.map(({ name, description, icon: Icon, status, latency, checked }) => <div key={name} className="flex flex-col gap-3 rounded-2xl border border-slate-100 p-4 sm:flex-row sm:items-center"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-slate-100"><Icon className="h-5 w-5" /></span><div className="flex-1"><p className="font-black">{name}</p><p className="text-xs text-slate-400">{description}</p></div><div className="flex items-center justify-between gap-6 sm:justify-end"><div className="text-right"><p className="text-xs font-black">{latency}</p><p className="text-[10px] text-slate-400">{checked}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-black ${status === '정상' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{status}</span></div></div>)}</div></Panel>
    <div className="space-y-6"><Panel><h2 className="text-lg font-black">API 키 설정</h2><div className="mt-4 space-y-3">{[['OPENAI_API_KEY', '••••••••7Km2'], ['TOUR_API_SERVICE_KEY', '••••••••9Qp1'], ['GOOGLE_MAPS_API_KEY', '••••••••2Aa8']].map(([key, mask]) => <div key={key} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-3"><KeyRound className="h-4 w-4 text-slate-400" /><div className="flex-1"><p className="text-[11px] font-black">{key}</p><p className="font-mono text-[10px] text-slate-400">{mask}</p></div><span className="text-[10px] font-black text-emerald-600">설정됨</span></div>)}</div></Panel><Panel><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-amber-500" /><h2 className="text-lg font-black">최근 알림</h2></div><div className="mt-4 rounded-2xl bg-amber-50 p-4"><p className="text-xs font-black text-amber-900">Google Maps 지연 증가</p><p className="mt-1 text-[11px] leading-5 text-amber-700">평균 응답이 기준값 800ms를 초과했습니다. fallback 이동시간은 정상 작동 중입니다.</p><p className="mt-2 flex items-center gap-1 text-[10px] text-amber-600"><Clock3 className="h-3 w-3" />12분 전</p></div></Panel></div>
  </div></> }
