import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, CalendarDays, MapPin, RefreshCw, Route, Users } from 'lucide-react';
import { adminTrips } from '../data';
import { Panel, StatusPill } from '../ui';

export function TripDetailPage() { const { id } = useParams(); const trip = adminTrips.find(item => item.id === id) ?? adminTrips[0]; return <>
  <Link to="/admin/trips" className="mb-5 inline-flex items-center gap-2 text-xs font-black text-slate-500"><ArrowLeft className="h-4 w-4" />여행 목록</Link>
  <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-3 flex items-center gap-2"><StatusPill value={trip.status} /><span className="text-xs font-bold text-slate-400">{trip.id}</span></div><h1 className="text-3xl font-black tracking-[-.04em]">{trip.title}</h1><p className="mt-2 text-sm text-slate-500">{trip.travelers.join('님 · ')}님이 함께 만드는 여행입니다.</p></div><div className="flex gap-2"><button className="flex h-11 items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 text-xs font-black"><RefreshCw className="h-4 w-4" />관광지 재생성</button><button className="flex h-11 items-center gap-2 rounded-2xl bg-[#17201f] px-4 text-xs font-black text-white"><Route className="h-4 w-4" />일정 재생성</button></div></div>
  <div className="grid gap-4 sm:grid-cols-4"><Info icon={<Users />} label="참여자" value={trip.travelers.join(', ')} /><Info icon={<MapPin />} label="지역" value={trip.region} /><Info icon={<CalendarDays />} label="기간" value={trip.period} /><Info icon={<Route />} label="일정 항목" value={`${trip.itineraryItems}개`} /></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_1.4fr]"><Panel><h2 className="text-lg font-black">공동 선호</h2><div className="mt-5 space-y-4">{[['여행 장소', '바다 · 로컬 골목 · 전시'], ['활동', '산책 · 사진 · 맛집'], ['여행 속도', '여유롭게 58%'], ['예산', '1인 60만원'], ['추가 옵션', '숨은 명소 선호']].map(([key, value]) => <div key={key} className="flex justify-between border-b border-slate-50 pb-3 text-sm"><span className="text-slate-400">{key}</span><span className="font-black">{value}</span></div>)}</div></Panel><Panel><div className="flex items-center justify-between"><h2 className="text-lg font-black">생성 기록</h2><span className="text-[11px] text-slate-400">최근 순</span></div><div className="mt-5 space-y-5">{[['일정 생성 완료', '오늘 14:32', 'success'], ['관광지 8곳 추천 완료', '오늘 14:28', 'success'], ['TourAPI 후보 42건 수집', '오늘 14:27', 'success'], ['공동 선호 저장', '오늘 14:25', 'success']].map(([title, time]) => <div key={title} className="flex gap-3"><span className="mt-1 h-2.5 w-2.5 rounded-full bg-emerald-500 ring-4 ring-emerald-50" /><div><p className="text-sm font-black">{title}</p><p className="mt-1 text-xs text-slate-400">{time}</p></div></div>)}</div></Panel></div>
  </> }
function Info({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-2xl border border-black/[.06] bg-white p-5"><span className="text-[#ff5a47]">{icon}</span><p className="mt-5 text-xs font-bold text-slate-400">{label}</p><p className="mt-1 font-black">{value}</p></div>; }
