import { Link } from 'react-router-dom';
import { CalendarDays, ChevronRight, MapPinned, Route, Search } from 'lucide-react';
import { adminTrips } from '../data';
import { PageHeading, Panel, StatusPill, TableShell, tdClass, thClass } from '../ui';

export function TripsPage() { return <><PageHeading eyebrow="Journeys" title="여행 관리" description="매칭 이후 생성된 공동 여행과 추천 관광지, 일정 생성 상태를 확인합니다." />
  <div className="mb-6 grid gap-4 sm:grid-cols-4"><TripMini label="계획 중" value="18" icon={<CalendarDays />} /><TripMini label="확정 여행" value="24" icon={<MapPinned />} /><TripMini label="이번 달 완료" value="67" icon={<Route />} /><TripMini label="생성 실패" value="3" danger /></div>
  <Panel><div className="relative mb-5 max-w-md"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input className="h-12 w-full rounded-2xl border border-slate-200 pl-11 pr-4 text-sm outline-none focus:border-[#ff5a47]" placeholder="여행명, 여행 ID, 참여자 검색" /></div><TableShell><thead><tr>{['여행', '참여자', '기간', '추천지', '일정', '상태', ''].map(x => <th key={x} className={thClass}>{x}</th>)}</tr></thead><tbody>{adminTrips.map(trip => <tr key={trip.id} className="hover:bg-slate-50/70"><td className={tdClass}><p className="font-black">{trip.title}</p><p className="mt-1 text-[11px] text-slate-400">{trip.id} · {trip.region}</p></td><td className={tdClass}><div className="flex -space-x-2">{trip.travelers.map(name => <span key={name} title={name} className="grid h-8 w-8 place-items-center rounded-full border-2 border-white bg-slate-200 text-[10px] font-black">{name[0]}</span>)}</div></td><td className={`${tdClass} text-slate-500`}>{trip.period}</td><td className={`${tdClass} font-black`}>{trip.attractions}곳</td><td className={`${tdClass} font-black`}>{trip.itineraryItems ? `${trip.itineraryItems}개` : '-'}</td><td className={tdClass}><StatusPill value={trip.status} /></td><td className={tdClass}><Link to={`/admin/trips/${trip.id}`} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200"><ChevronRight className="h-4 w-4" /></Link></td></tr>)}</tbody></TableShell></Panel></> }
function TripMini({ label, value, icon, danger }: { label: string; value: string; icon?: React.ReactNode; danger?: boolean }) { return <div className="rounded-2xl border border-black/[.06] bg-white p-5"><div className={danger ? 'text-rose-500' : 'text-slate-400'}>{icon}</div><p className="mt-5 text-xs font-bold text-slate-400">{label}</p><p className={`mt-1 text-2xl font-black ${danger ? 'text-rose-600' : ''}`}>{value}</p></div>; }
