import { BookOpenCheck, Edit3, Eye, Plus, Sparkles } from 'lucide-react';
import { ttiQuestions } from '../data';
import { PageHeading, Panel, TableShell, tdClass, thClass } from '../ui';

export function TtiPage() { return <><PageHeading eyebrow="Personality content" title="TTI 콘텐츠" description="여행 성향 질문과 16개 여행 유형을 확인합니다. 배포 기능은 API 연결 후 활성화됩니다." action={<button className="flex h-11 items-center gap-2 rounded-2xl bg-[#17201f] px-4 text-xs font-black text-white"><Plus className="h-4 w-4" />질문 추가</button>} />
  <div className="mb-6 grid gap-4 sm:grid-cols-3"><TtiMini icon={<BookOpenCheck />} label="활성 질문" value="12" /><TtiMini icon={<Sparkles />} label="여행 유형" value="16" /><TtiMini icon={<Eye />} label="현재 버전" value="v1.0" /></div>
  <Panel><div className="mb-6 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-lg font-black">진단 질문</h2><p className="mt-1 text-xs text-slate-400">4개 성향 축 · 축별 3문항</p></div><div className="flex gap-2">{['전체', 'PW', 'NC', 'FA', 'HS'].map((axis, i) => <button key={axis} className={`rounded-xl px-3 py-2 text-xs font-black ${i === 0 ? 'bg-[#17201f] text-white' : 'bg-slate-100 text-slate-500'}`}>{axis}</button>)}</div></div>
    <TableShell><thead><tr>{['순서', '축', '질문', '상태', '수정'].map(x => <th key={x} className={thClass}>{x}</th>)}</tr></thead><tbody>{ttiQuestions.map(item => <tr key={item.id} className="hover:bg-slate-50/70"><td className={`${tdClass} font-black text-slate-400`}>{String(item.order).padStart(2, '0')}</td><td className={tdClass}><span className="rounded-lg bg-[#fff0ed] px-2.5 py-1.5 text-xs font-black text-[#ff5a47]">{item.axis}</span></td><td className={`${tdClass} font-bold`}>{item.prompt}</td><td className={tdClass}><span className="inline-flex items-center gap-1.5 text-xs font-bold text-emerald-700"><i className="h-2 w-2 rounded-full bg-emerald-500" />활성</span></td><td className={tdClass}><button className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200"><Edit3 className="h-4 w-4" /></button></td></tr>)}</tbody></TableShell>
    <div className="mt-5 rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-4 text-center text-xs font-bold text-slate-400">나머지 7개 질문은 페이지네이션 영역에 표시됩니다.</div>
  </Panel></> }
function TtiMini({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center gap-4 rounded-2xl border border-black/[.06] bg-white p-5"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#fff0ed] text-[#ff5a47]">{icon}</span><div><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div></div>; }
