import { useMemo, useState } from 'react';
import { Download, Search, SlidersHorizontal, UserPlus } from 'lucide-react';
import { adminUsers, type AdminUserStatus } from '../data';
import { PageHeading, Panel, StatusPill, TableShell, tdClass, thClass } from '../ui';

export function UsersPage() {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState<'all' | AdminUserStatus>('all');
  const rows = useMemo(() => adminUsers.filter(user => (status === 'all' || user.status === status) && `${user.nickname} ${user.email} ${user.ttiCode}`.toLowerCase().includes(query.toLowerCase())), [query, status]);
  return <><PageHeading eyebrow="People" title="회원 관리" description="가입 회원의 TTI, 매칭 및 여행 활동과 계정 상태를 관리합니다." action={<button className="flex h-11 items-center gap-2 rounded-2xl bg-[#17201f] px-4 text-xs font-black text-white"><Download className="h-4 w-4" />CSV 내보내기</button>} />
    <div className="mb-6 grid gap-4 sm:grid-cols-3"><Mini label="전체 회원" value="1,284" /><Mini label="이번 주 가입" value="+86" accent /><Mini label="정지 계정" value="12" /></div>
    <Panel><div className="mb-5 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} className="h-12 w-full rounded-2xl border border-slate-200 pl-11 pr-4 text-sm outline-none focus:border-[#ff5a47]" placeholder="닉네임, 이메일, TTI 검색" /></div><div className="flex items-center gap-2"><SlidersHorizontal className="h-4 w-4 text-slate-400" /><select value={status} onChange={e => setStatus(e.target.value as typeof status)} className="h-12 rounded-2xl border border-slate-200 bg-white px-4 text-sm font-bold"><option value="all">전체 상태</option><option value="active">정상</option><option value="suspended">정지</option><option value="withdrawn">탈퇴</option></select></div></div>
      <TableShell><thead><tr>{['회원', '지역 / TTI', '가입일', '매칭', '여행', '상태', ''].map(x => <th className={thClass} key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(user => <tr key={user.id} className="hover:bg-slate-50/70"><td className={tdClass}><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-slate-100 font-black">{user.nickname[0]}</span><div><p className="font-black">{user.nickname}</p><p className="text-xs text-slate-400">{user.email}</p></div></div></td><td className={tdClass}><p className="font-bold">{user.region}</p><p className="text-xs font-black text-[#ff5a47]">{user.ttiCode}</p></td><td className={`${tdClass} text-slate-500`}>{user.joinedAt}</td><td className={`${tdClass} font-black`}>{user.matches}</td><td className={`${tdClass} font-black`}>{user.trips}</td><td className={tdClass}><StatusPill value={user.status} /></td><td className={tdClass}><button className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-black hover:border-[#ff5a47]">상세 보기</button></td></tr>)}</tbody></TableShell>
      <div className="mt-5 flex items-center justify-between text-xs font-bold text-slate-400"><span>총 {rows.length}명 표시</span><div className="flex gap-1"><button className="rounded-lg bg-[#17201f] px-3 py-2 text-white">1</button><button className="rounded-lg px-3 py-2">2</button><button className="rounded-lg px-3 py-2">3</button></div></div>
    </Panel></>;
}
function Mini({ label, value, accent }: { label: string; value: string; accent?: boolean }) { return <div className={`rounded-2xl border border-black/[.06] p-5 ${accent ? 'bg-[#fff0ed]' : 'bg-white'}`}><p className="text-xs font-bold text-slate-400">{label}</p><p className={`mt-2 text-2xl font-black ${accent ? 'text-[#ff5a47]' : ''}`}>{value}</p></div>; }
