import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

const questions = ['여행 일정의 시작 시간', '하루 이동량', '대표 관광지 비중', '식사 예산'];

export function Step3ConcessionPage() {
  const navigate = useNavigate();
  const [answers, setAnswers] = useState<Record<number, string>>({});
  const count = Object.keys(answers).length;
  return <main className="page form-page"><div className="form-toolbar"><button onClick={() => navigate('/proposal')}>‹ 조율로 돌아가기</button><span>{count} / {questions.length} 작성</span><div className="form-progress"><i style={{ width: String((count / questions.length) * 100) + '%' }} /></div></div><article className="paper"><header className="paper-head"><h1>양보 범위 조사서</h1><p>ODDTRIP FORM 03 · PRIVATE CONCESSION</p></header><div className="paper-body"><p className="paper-note">개인별 비공개 제출 화면의 정보 구조입니다. 현재 백엔드는 이 응답을 사용자별로 저장하지 않으므로 입력은 화면을 벗어나면 사라집니다.</p><div className="document-lock"><b>백엔드 연결 대기</b><br />제출·임시 저장을 성공으로 위조하지 않습니다. 개인별 응답 스키마와 양쪽 제출 상태 API가 필요합니다.</div><div className="info-table"><span className="label">문서</span><span>개인 양보안</span><span className="label">공개 범위</span><span>연결 후 비공개</span><span className="label">저장 상태</span><span>저장되지 않음</span><span className="label">계약</span><span>미지원</span></div><h2 className="form-section-title">1. 항목별 응답</h2>{questions.map((question, index) => <section className="question" key={question}><div className="question-head"><b>{String(index + 1).padStart(2, '0')}</b><span>{question}</span></div><div className="option-list">{['지키고 싶어요', '조율 가능해요', '상대에게 맡길게요'].map((option) => <button className={answers[index] === option ? 'on' : ''} key={option} onClick={() => setAnswers((current) => ({ ...current, [index]: option }))}>{answers[index] === option ? '✓' : '□'} {option}</button>)}</div></section>)}<h2 className="form-section-title">2. 동행에게 미리 전할 내용</h2><textarea placeholder="현재는 저장되지 않습니다." /><div className="sign"><span>미제출 문서</span><span>작성자 서명 __________</span></div></div></article><div className="form-actions"><button onClick={() => navigate('/proposal')}>작성 취소</button><span className="hint">입력 {count}개 · 저장 API 없음</span><button className="submit unsupported-button" disabled>백엔드 연결 대기</button></div></main>;
}
